import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import { getSession } from "@auth0/nextjs-auth0";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JobFunnel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session?.user;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <menu className="flex items-center bg-white">
            <Image src="/logo.webp" alt="logo" width={40} height={40} />
            <h1 className="text-2xl font-bold italic px-2">jobfunnel</h1>
            <div className="grow px-2 text-right">
              {user ? (
                <span>
                  Hi, {user.name} (<a href="/api/auth/logout">Logout</a>)
                </span>
              ) : (
                <a href="/api/auth/login">Login</a>
              )}
            </div>
          </menu>
          <UserProvider>{children}</UserProvider>
        </Providers>
      </body>
    </html>
  );
}
